# Generated by Django 3.2.6 on 2021-11-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='opening_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='total_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
