# Generated by Django 3.2.6 on 2022-01-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '__first__'),
        ('users', '0002_auto_20211122_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fateher_name',
            new_name='father_name',
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='father_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_institute', to='college_data.institute'),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avtar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Avtar',
        ),
    ]
