# Generated by Django 3.2.6 on 2021-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211124_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avtar/'),
        ),
        migrations.DeleteModel(
            name='Avtar',
        ),
    ]
