# Generated by Django 3.2.6 on 2021-11-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211124_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
