# Generated by Django 3.2.6 on 2021-11-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211124_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
