# Generated by Django 3.2.6 on 2021-11-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_institute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fateher_name',
            new_name='father_name',
        ),
    ]
