# Generated by Django 3.2.9 on 2021-12-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_fateher_name_user_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='', max_length=20),
        ),
    ]
