# Generated by Django 3.2.6 on 2021-12-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0008_delete_semesterwisestudent'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feegroup',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.institute'),
        ),
        migrations.AlterField(
            model_name='feegroup',
            name='term_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.feeterm'),
        ),
        migrations.AlterField(
            model_name='feeterm',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.institute'),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.institute'),
        ),
    ]
