# Generated by Django 3.0.8 on 2020-12-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_short_name',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
