# Generated by Django 3.2.6 on 2021-11-23 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college_data', '0003_auto_20211124_0135'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateTimeField()),
                ('student_status', models.CharField(blank=True, choices=[('current', 'CURRENT'), ('dropout', 'DROPOUT'), ('passout', 'PASSOUT')], default='current', max_length=50)),
                ('student_religion', models.CharField(blank=True, choices=[('hindu', 'HINDU'), ('muslim', 'MUSLIM'), ('sikh', 'SIKH'), ('ishi', 'ISHI')], max_length=50, null=True)),
                ('student_category', models.CharField(blank=True, choices=[('general', 'GENERAL'), ('ebc', 'EBC'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST')], max_length=50, null=True)),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.department')),
                ('session_admitted', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
    ]
