# Generated by Django 3.2.6 on 2021-11-27 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college_data', '0008_delete_semesterwisestudent'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterWiseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(blank=True, null=True)),
                ('semester_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_data.semestersession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'semester_wise_student',
            },
        ),
    ]
