# Generated by Django 3.2.6 on 2021-11-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_semesterwisestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
