# Generated by Django 3.2.6 on 2021-11-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0008_delete_semesterwisestudent'),
        ('student', '0003_alter_studentprofile_date_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.department'),
        ),
    ]
