# Generated by Django 3.2.6 on 2021-11-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0008_delete_semesterwisestudent'),
        ('student', '0004_alter_studentprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='session_admitted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.session'),
        ),
    ]
