# Generated by Django 3.2.6 on 2021-11-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0008_delete_semesterwisestudent'),
        ('student', '0005_alter_studentprofile_session_admitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='session_admitted',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.semestersession'),
        ),
    ]
