# Generated by Django 3.2.6 on 2021-11-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0008_delete_semesterwisestudent'),
        ('student', '0007_auto_20211127_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='semester_session',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester_admit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.session'),
        ),
    ]
