# Generated by Django 3.2.6 on 2021-11-28 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20211128_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterwisestudent',
            name='assigned_on',
        ),
        migrations.AddField(
            model_name='semesterwisestudent',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
