# Generated by Django 3.2.6 on 2021-11-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20211128_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='semester_admit',
            new_name='session_admit',
        ),
    ]
