# Generated by Django 3.2.6 on 2021-11-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_designation_staffprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='Qualification',
            new_name='qualification',
        ),
    ]
