# Generated by Django 3.2.6 on 2021-12-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_rename_qualification_staffprofile_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
