# Generated by Django 3.2.6 on 2021-11-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='session',
            table='session',
        ),
    ]
