# Generated by Django 3.2.6 on 2021-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0004_institute_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='affilation_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='api_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='college_image/'),
        ),
        migrations.AddField(
            model_name='institute',
            name='office_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='registration_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='website_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
