# Generated by Django 3.2.6 on 2021-11-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0005_auto_20211125_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
