# Generated by Django 3.2.6 on 2021-11-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0006_auto_20211126_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='current_session',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
