# Generated by Django 3.2.6 on 2021-11-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0007_auto_20211127_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemesterWiseStudent',
        ),
    ]
