# Generated by Django 3.2.9 on 2021-12-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0008_delete_semesterwisestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='username_prefix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
