# Generated by Django 3.2.9 on 2021-12-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0009_institute_username_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='username_prefix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
