# Generated by Django 3.2.9 on 2021-12-04 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_data', '0010_alter_institute_username_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersession',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_data.session'),
        ),
    ]
